# docker compose -f docker-compose.dev.yml up --build -d
# OU
# docker compose -f docker-compose.dev.yml build --no-cache
# docker compose -f docker-compose.dev.yml up -d
# API → http://localhost:8000/docs
# Frontend → http://localhost:8501

# Pour débuguer: docker compose -f docker-compose.dev.yml build --no-cache --progress=plain

services:
  api:
    build: ./backend
    container_name: fastapi_backend_dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - ENV=development
      - RELOAD=true
      - PYTHONUNBUFFERED=1
    networks:
      - appnet
    stdin_open: true
    tty: true
    command: uvicorn api:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app

  streamlit:
    build: ./frontend
    container_name: streamlit_frontend
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - appnet

networks:
  appnet:
